# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
airline = Airline.create!(name: 'Frontier')
flight = airline.flights.create!(flight_number: 4, airline_id: airline.id)
john = flight.passengers.create(name: "John", age: 28)
mary = flight.passengers.create(name: "Mary", age: 29)
olaf = flight.passengers.create(name: "Olaf", age: 29)
flight.passengers.create(name: "Terry", age: 43)
flight.passengers.create(name: "Gary", age: 68)
flight.passengers.create(name: "Larry", age: 18)
flight.passengers.create(name: "Jerry", age: 35)

flight = airline.flights.create!(flight_number: 7, airline_id: airline.id)
flight.flight_passengers.create(passenger_id: john.id)
flight.flight_passengers.create(passenger_id: mary.id)
millie = flight.passengers.create(name: "Millie", age: 28)
flight.passengers.create(name: "Willie", age: 29)
flight.passengers.create(name: "Billie", age: 43)
flight.passengers.create(name: "Gill", age: 68)
flight.passengers.create(name: "Bill", age: 18)
flight.passengers.create(name: "Will", age: 35)

flight = airline.flights.create!(flight_number: 10, airline_id: airline.id)
flight.flight_passengers.create(passenger_id: millie.id)
flight.flight_passengers.create(passenger_id: olaf.id)
sherry = flight.passengers.create(name: "Sherry", age: 28)
flight.passengers.create(name: "Carry", age: 29)
flight.passengers.create(name: "Barry", age: 43)
flight.passengers.create(name: "Larry", age: 68)
flight.passengers.create(name: "Sarah", age: 18)
flight.passengers.create(name: "Carah", age: 35)

flight = airline.flights.create!(flight_number: 22, airline_id: airline.id)
flight.flight_passengers.create(passenger_id: olaf.id)
flight.flight_passengers.create(passenger_id: sherry.id)
flight.passengers.create(name: "Molag", age: 28)
flight.passengers.create(name: "Bolaf", age: 43)
flight.passengers.create(name: "Dolaf", age: 68)
flight.passengers.create(name: "Bulog", age: 18)
flight.passengers.create(name: "Tim", age: 35)

flight = airline.flights.create!(flight_number: 43, airline_id: airline.id)
flight.flight_passengers.create(passenger_id: olaf.id)
flight.passengers.create(name: "Sam", age: 28)
flight.passengers.create(name: "Pam", age: 29)
flight.passengers.create(name: "Cam", age: 43)
flight.passengers.create(name: "Dill", age: 68)
flight.passengers.create(name: "Phil", age: 18)
flight.passengers.create(name: "Quill", age: 35)
